service: omni-finance-search-portal-backend # Change this to your service name

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  runtime: nodejs20.x
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DetachNetworkInterface
        - ec2:DeleteNetworkInterface
        - ec2:AssignPrivateIpAddresses
        - ec2:UnassignPrivateIpAddresses
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'batch:Describe*'
        - 'batch:List*'
        - 'batch:SubmitJob'
      Resource: '*'     
  environment:
    STAGE: ${self:provider.stage}
    ERROR_SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    # REDIS_ENDPOINT: finance-search-portal-redis-1-dev.cbgmpe.ng.0001.use1.cache.amazonaws.com:6379
    REDIS_ENDPOINT: ${ssm:/omni-finance-search-portal/${self:provider.stage}/redis-endpoint}

  deploymentBucket:
    name: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
    serverSideEncryption: AES256

package:
  individually: true

plugins:
  - serverless-offline

functions:
  omni-finance-search: ${file(config/functions/search.yml):function}
  omni-finance-redis-loader: ${file(config/functions/redis-loader.yml):function}

layers:
  NodeModules:
    path: lambdaLayer/lib
    name: ${self:service}-layer-${self:provider.stage}
    description: Lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs20.x
    retain: false

resources:
  Resources:
    # shipment header full load batch
    HelloWorldBatchServiceRole: ${file(config/batch/computeEnvironment.yml):HelloWorldBatchServiceRole}
    HelloWorldComputeEnvironment: ${file(config/batch/computeEnvironment.yml):HelloWorldComputeEnvironment}
    HelloWorldJobQueue: ${file(config/batch/redisSampleJobQueue.yml):HelloWorldJobQueue}
    HelloWorldBatchTaskExecutionRole: ${file(config/batch/redisSampleJob.yml):OmniRtBatchTaskExecutionRole}
    HelloWorldJobDefinition: ${file(config/batch/redisSampleJob.yml):ShipmentHeaderJobDefinition}
    HelloWorldBatchLogGroup: ${file(config/batch/redisSampleJob.yml):ShipmentHeaderBatchLogGroup}