HelloWorldJobQueue:
  Type: AWS::Batch::JobQueue
  Properties:
    JobQueueName: hello-world-job-queue-${self:provider.stage}
    ComputeEnvironmentOrder:
      - Order: 1
        ComputeEnvironment:
          Ref: HelloWorldComputeEnvironment
    State: ENABLED
    Priority: 1